---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(earth)
master<-read.csv("C:\\Users\\gmandl\\Documents\\GitHub\\DATA495.github.io\\Data\\NHANES\\master_depression.csv")
```

```{r}
master2 <- drop_na(master)
rownames(master2) <- as.integer(master2$SEQN)
master2 <- master2 |> select(-SEQN)
smp_size<-floor(0.75*nrow(master2))
train_ind <- sort(sample(nrow(master2), nrow(master2)*.7))

train <- master2[train_ind, ]
test <- master2[-train_ind,]
```

```{r}
library(caret)
hyper_grid <- expand.grid(
  degree = 1:3, 
  nprune = seq(2, 100, length.out = 10) %>% floor()
)
cv_mars <- train(
  x = subset(master2, select = -DepressionScore),
  y = master2$DepressionScore,
  method = "earth",
  metric = "RMSE",
  trControl = trainControl(method = "cv", number = 10),
  tuneGrid = hyper_grid
)

print(mars1)
```
```{r}

vip(cv_mars, num_features = 10, geom = "point") + ggtitle("Feature Importance")
```  

```{r}
pdp::partial(cv_mars, pred.var = "LBXRDW", grid.resolution = 10) |> autoplot()+ggtitle("Partial Relationship of Red Cell Distribution Width") + xlab("Red Cell Distribution Width (%)") + ylab("Target Variable")
```

```{r}
mars1$weights
```

